name: 'Upload to GitHub'
author: 'LasyIsLazy'
description: 'Upload file to your GitHub repository with Node.js'
branding:
  icon: 'upload'
  color: 'white'
inputs:
  access-token:
    description: 'Token access to repository'
    required: true
  file-path:
    description: 'Local file path/directory'
    required: true
  username:
    description: 'GitHub username'
    required: true
  repo:
    description: 'Repository name'
    required: true    
  branchName:
    description: 'Branch name to upload the file to'
    required: true
  remote-dir:
    description: 'Remote repository file path/directory, default: The root of repository'
    required: false
    default: ''
  commit-message:
    description: 'Git commit message, default: "upload"'
    required: false
    default: 'upload'
runs:
  using: 'node12'
  main: 'index.js'
